### ISSUE TITLE
Allow "subscribe all"

### ISSUE THREAD

**Issue by marcoancona** [mroderick/PubSubJS#102]
I would like to intercept all topics. I suggest the empty string, or the wildcard character, to subscribe to all topics. Since hierarchical addressing is already there, I find quite natural to be able to use

```js
PubSub.subscribe('', (message, data) => {
// Triggered with any message
})
```
to capture all topics at once.

**Comment by subinvarghesein** [comment]
An explicit character like `*` would be better than an empty string

**Comment by shaneporter** [comment]
Or a dedicated, `subscribeAll` function?

**Comment by marcoancona** [comment]
Both makes sense. I like the `subscribeAll` idea. On my fork I just used the empty string cause it only requires to add 2 lines: https://github.com/marcoancona/PubSubJS/commit/14c456e8c1668d807b4802f4088d98b5daf79e3a

**Comment by mroderick** [comment]
I like the idea of an explicit function for this purpose. Expecting the readers of our software to interpret magic strings often leads to mistakes.

**Comment by subinvarghesein** [comment]
Yup a dedicated function would be a better idea

**Comment by xdvarpunen** [comment]
+1 to named dedicated function, helps readability

**Comment by roschaefer** [comment]
I prefer not to use a dedicated function. If the existing behaviour is a dot notation like `topic.subtopic` I find it counter-intuitive to use a different function just to do the same thing.

`null`, `'*'`, `''` and `'.'` is all fine for me. :thinking: I would like `'.'` the most (similar to the current folder in UNIX systems).
