### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by dazinator** [mroderick/PubSubJS#104]
Does anyone know if there are typescript definition files available for this library?

**Comment by mroderick** [comment]
@dazinator did you find an answer to your question?

**Comment by dazinator** [comment]
I manually created a typescript definition file in the end, wasn't much to it, as pub sub methods are very simple.

**Comment by shadowbrush** [comment]
This will get you the definitions: `yarn add -D @types/pubsub-js`

**Comment by Febriantos** [comment]
This file is generated using dts-gen https://github.com/microsoft/dts-gen
[pubsub-js.d.txt](https://github.com/mroderick/PubSubJS/files/3575819/pubsub-js.d.txt)
