### ISSUE TITLE
PubSub Doesn't Work Across Windows

### ISSUE THREAD

**Issue by ijabit** [mroderick/PubSubJS#105]
If I use window.open, and need to publish an event that a subscriber in the new window is listening to, it doesn't work. Is there a way to get PubSubJS to publish events cross-window?

**Comment by mroderick** [comment]
For that you need to use something like [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage).

**Comment by ijabit** [comment]
What I ended up doing was to get a reference to the PubSubJS object from the returned Window object.  I use the same JS file to run both the in-window and the popup window. Now if the event is one that I want to pass on to the popup window, I can just re-publish it to the other Window object! It works great. It would be cool if PubSubJS could do this automatically, but what I've got is way better than the old postMessage stuff.

```
PubSub.subscribe("myTopic", (topic: string, data: any) => {
    if (this.isPoppedOut === true && this.isRunningInsidePopupWindow === false) {
        this.passEventToPopupWindow(topic, data);
    } else {
        // handle event here
    }
}

function passEventToPopupWindow(topic: string, data: any) {
    this.popUpWindowViewModel.myPubSubJsReference.publish(topic, data);
    this.popUpWindow.focus();
}
```
