### ISSUE TITLE
Unsubscribe from the top level does not work if subscribed to child messages individually

### ISSUE THREAD

**Issue by ogvolkov** [mroderick/PubSubJS#106]
I've found that a blanket unsubscription works only if we were subscribed to the root level explicitly. The following code, for example, will not remove the 'a.b' subscription:

```
PubSub.subscribe('a.b', function () { console.log("a.b"); });
PubSub.unsubscribe('a');
PubSub.publish('a.b');

```
Is it by design, and if so – why? It seems to be much more convenient to be able to unsubscribe from the whole hierarchy without having to subscribe to the top level every time.

**Comment by ogvolkov** [comment]
I'd love to, but unfortunately I cannot even run tests because I'm using Windows (yes, I'm THAT kind of a person), and tests fail because of $ usage in paths.

I hope to revisit it later - at least it's good to know that the behavior is not by design.

**Comment by shaneporter** [comment]
I've used this project's code extensively on a project or two of my own, so I'd like to give something back if I can. Can take a look at this when I get a chance.

**Comment by mroderick** [comment]
> I've used this project's code extensively on a project or two of my own, so I'd like to give something back if I can. Can take a look at this when I get a chance.

That would be very welcome :)
