### ISSUE TITLE
Tag repo for versions 1.5.5 and 1.5.6

### ISSUE THREAD

**Issue by chrisbroome** [mroderick/PubSubJS#109]
### Problem

NPM is showing that versions `1.5.5` and `1.5.6` were published, but the tags haven't been added to this repo.

### Solution

Using `npm` we see the relevant commits:

`npm view pubsub-js@1.5.5 gitHead`
2215fff8625b3ea29cfccc9aef02e7f7aa0d9f27

`npm view pubsub-js@1.5.6 gitHead`
38800db48fe5b855c2c7d75903d07740ce5c63d6

### Second problem (maybe separate issue)
Published version `1.5.5` with `gitHead`: `2215fff8625b3ea29cfccc9aef02e7f7aa0d9f27` does not exist in this repo.

### Solution
Push the commit `2215fff8625b3ea29cfccc9aef02e7f7aa0d9f27` here

**Comment by mroderick** [comment]
I (believe) I have fixed the issue now.

Thank you for reporting this with great detail!
