### ISSUE TITLE
Missing bower.json

### ISSUE THREAD

**Issue by JeremyRann** [mroderick/PubSubJS#113]
Version 1.5.7 of PubSubJS appears to be missing a bower.json file, which specifies the main entry point for tools that speak bower's syntax. In my app, my grunt wiredep step skips adding PubSubJS to my project because it can't find the main entry point, but it worked in 1.5.4. For now I'm just locking to the old version, but newer PubSubJS should probably include a main entry point in a bower.json file (it was previously src/pubsub.js, and I think that's still valid). I wouldn't be surprised if not including a bower.json file causes other issues; wiredep is just what my app happened to fail on.

**Comment by philipjfulcher** [comment]
I have also run into this problem. I'm locking my version to 1.5.4 until this is resolved.

**Comment by mroderick** [comment]
`bower.json` has been removed since [bower has been deprecated](https://bower.io)

**Comment by philipjfulcher** [comment]
I think there should be some better communication around this. The bower home page doesn't say deprecated, it says it's being maintained. If you want to drop bower support from the project, then that should be communicated clearly to consumers. Right now, the README still lists a bower version and a bower installation method. This could also been handled with a major version change, indicating a breaking change. As it is, I had my bower version for PubSub set to ~1.5.4. I was automatically updated to this newly published version (1.5.7) that does not have a bower.json included. Or maybe the latest version shouldn't have been published to bower.

I know projects at my company will still be using bower at least through the end of the year. We have a long-term project that's going to take a little while to build a new build process around npm, yarn, or webpack.

**Comment by JeremyRann** [comment]
If bower isn't supported anymore, the latest available version available on bower should be 1.5.4. Publishing 1.5.7 but leaving bower.json out isn't dropping bower support, it's intentionally breaking bower builds. I don't particularly care for bower either (I inherited it on this project), but this is a pretty poor way to handle the handoff.

**Comment by mroderick** [comment]
> I would have appreciated any approach that didn't break my build process in the middle of the workday.

Don't use loose versioning.

**Comment by mroderick** [comment]
The fact that bower uses git tags is a double edged sword. It was really amazing when the community was moving into bower ... it's not so amazing when we're moving away from it, and it is so easily broken.

I will continue to use git tags for versioning my projects, I suspect many other projects will as well. This situation is likely to arise again and again, so if you continue to use bower, you're going to have to find solutions to this.

**Comment by mroderick** [comment]
@JeremyRann considering that bower uses git tags, I don't see how this situation can be avoided. Ideas welcome

**Comment by JeremyRann** [comment]
I see - I didn't realize publishing to bower was automatic via tags. You're right that it's definitely a double-edge sword in that case. I wonder if it's possible to unregister a package so that future versions won't be published but existing versions remain? The documentation for unregister on bower's docs seems really slim, so I'm not even sure what it does.

Regardless, seeing how this went I suspect this will be a continual problem with bower that gets worse and worse as time goes on. I think I may do as you suggest simply lock all package versions now, but that's certainly pointing me towards migrating off of it sooner. Thanks for the clarification. You might want to consider noting the issue in the package readme; knowing that 1.5.4 still works in bower is a helpful stop-gap.

**Comment by mroderick** [comment]
> The documentation for unregister on bower's docs seems really slim, so I'm not even sure what it does.

Indeed. If I read the [unregister section](https://bower.io/docs/creating-packages/#unregister) correctly, then it'll remove the package entirely. That would be an even bigger mess.

**Comment by mroderick** [comment]
> You might want to consider noting the issue in the package readme; knowing that 1.5.4 still works in bower is a helpful stop-gap.

Great idea! I have updated the README to reflect that
