### ISSUE TITLE
don't directly use hasOwnProperty

### ISSUE THREAD

**Issue by ihtml5** [mroderick/PubSubJS#115]
## Suggestions:
```javascript
var nativeHasOwn = Object.prototype.hasOwnProperty;
// use nativeHasOwn insteadof hasOwnProperty
```
## relate links
1. [mdn hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#Using_hasOwnProperty_as_a_property_name)
2. [Completely remove Object.prototype.hasOwnProperty.call](https://github.com/facebook/react/pull/7853)

**Comment by mroderick** [comment]
Fancy making a pull request for this?
