### ISSUE TITLE
Read previous events?

### ISSUE THREAD

**Issue by jcguarinpenaranda** [mroderick/PubSubJS#124]
Hello, 

I am wondering if it is possible to read previous published events, I am using this for an application in which when it starts, I emit an event with the current user.

I am wondering if there's any way I can read this previously sent event to get the current user in React components that are mounted after the app starts.

**Comment by mroderick** [comment]
There’s no support for that in the library. 

I imagine that it wouldn’t be very difficult for you to create a little thing that keeps the last n events for a few minutes, and then just ask that for the event you’re interested in

**Comment by jcguarinpenaranda** [comment]
Thank you,

I wrote a library that does this, but replaying only the last event, It's https://github.com/owsas/pubsub-replay.

**Comment by mroderick** [comment]
Very cool!

If I can mak a suggestion, it would be to avoid Boolean arguments. When looking at the call site, it’s very difficult to figure out what it means.

https://ariya.io/2011/08/hall-of-api-shame-boolean-trap

Instead you can rename the method, or pass an options argument with names keys that describe your intention

**Comment by jcguarinpenaranda** [comment]
That's a great advice, thank you so much!

2017-12-11 16:37 GMT-05:00 Morgan Roderick <notifications@github.com>:
