### ISSUE TITLE
Support subscription to topics by their type

### ISSUE THREAD

**Issue by omidkrad** [mroderick/PubSubJS#129]
See [aurelia/event-aggregator](https://github.com/aurelia/event-aggregator/blob/master/src/index.js) as an example of pubsub that can accept topics as strings or as classes. Basically, you can subscribe to a class and then the event aggregator will use the type of the class as the topic for messaging. Any object published that is `instanceof` a subscribed class is received by the subscribers to that class. I believe this is a powerful feature and especially works great with TypeScript since the subscribers know the exact type of the incoming message.

**Comment by mroderick** [comment]
That’s an interesting use case. However, it is divergent from the goals of this library. You could fork it and scratch your own itch
