### ISSUE TITLE
PubSub.publish returns false on the third time it's called

### ISSUE THREAD

**Issue by CViniciusSDias** [mroderick/PubSubJS#133]
I have two buttons that call PubSub.publish('topic', data), and it seems to work fine the first time I click each button. The third time it should publish the event, nothing happens and the method returns false.

**Comment by OasisLiveForever** [comment]
I have the same problem, I'm using PubSub in a React application and the third time I call  PubSub.publish, it return false.

**Comment by mroderick** [comment]
Can you create a runnable, minimal example that shows the error?

**Comment by OasisLiveForever** [comment]
[test-pubsub.zip](https://github.com/mroderick/PubSubJS/files/2745425/test-pubsub.zip)

I created a simple app where I publish an event in componentDidMount. publish method return false.

**Comment by OasisLiveForever** [comment]
I understood the problem: publish returns false if there is no subscription to the event.
