### ISSUE TITLE
Synchronous publication

### ISSUE THREAD

**Issue by ghost** [mroderick/PubSubJS#134]
The doc says: 

> For the adventurous, PubSubJS also supports synchronous topic publication. This can give a speedup in some environments (browsers, not all), but can also lead to some very difficult to reason about programs, where one topic triggers publication of another topic in the same execution chain.

Can you explain why synchronous publication leads to very difficult to reason about programs?
Why is it problematic when one topic triggers publication of another topic in the same execution chain? (in synchronous mode).

Because synchronous publication would seem more natural to me.

**Comment by mroderick** [comment]
If you think of it as [tree traversal](https://en.wikipedia.org/wiki/Tree_traversal), then synchronous publishing is equivalent to depth-first traversal, while asynchronous publishing is equivalent to breadth-first traversal.

Keep in mind that for every node, more nodes can be added to the tree.

If synchronous is more natural to you, feel free to use that:

```js
PubSub.publishSync('MY TOPIC', 'hello world!');
```
