### ISSUE TITLE
 messageHasSubscribers  cannot find subscribers

### ISSUE THREAD

**Issue by vladp** [mroderick/PubSubJS#137]
Hello
this is probably not a bug, but I hope I could get some guidance where to look.

I have been using pubsub across my app successfully.

And for the last couple of days days (after a node_module refresh, upgrade to React 16.4.1  and some light changes) -- I am observing
that my publication across several js modules does not work anymore.

Tracing it through, I can see that
All the subscriptions are going on fine, all the tokens are stored in appropriate class instances/etc.

However, when I call **publishSync**  , I get a 'false'.
And while debugging through that, I see that
 **messageHasSubscribers**  cannot find my subscribers.  And that happens because   **messages** object, that keeps the relation between subscribers and objects -- is completely empty, as if there were never any subscriptions.

As if somebody is clearing the messages object (it was populated by my subscribers when they were subscribing, no problem.

Therefore, I am wondering if I have some fundamental problem and PubSub is being instantiated somehow more than once, and just recently I started getting this due to just some module rearrangements...

What I wanted to ask, is 

a) am I including PubSub correctly by doing?
`import PubSub  from 'pubsub-js'`

(the readme does not include examples of how to include the module, so I was assuming the above is supported)

b) is it possible to include the module more than once (using the above method). That by using the import statements from multiple js files.

c) could there be a potential conflict if a package in one of the several hundreds npm modules, that I am using, is also using pubsub-js ?

d) are there any switches/or other guidance you could share of where to look at ?

Thank you advance,
and apologies for posting a not-a-bug on this forum, if there is better place to ask these kinds of questions --pls let me know.

**Comment by vladp** [comment]
found that using

var PubSub = global.PubSub || require('pubsub-js'),

instead of the **import** , as I was doing before  -- solves the problem.
the `import xxx` does not insure a single global instance, but PubSub relies on being instantiated only once.

**Comment by mroderick** [comment]
👍
