### ISSUE TITLE
Need to know if a topic is subscribed

### ISSUE THREAD

**Issue by pkalwar** [mroderick/PubSubJS#146]
Hi Morgan,
Thanks for this library. 

My use case is that I need to know if a topic is subscribed by atleast one listener/consumer to do the work (get data via ajax). There is already a method 'messageHasSubscribers' but not part of public api. 
Can there be a public method like "isTopicSubscribed" or "getCountOfSubscribers" for a topic passed-in?

Thank you.

**Comment by mroderick** [comment]
That seems reasonable. Would you like to contribute a pull request that implements it?

**Comment by zamhaq** [comment]
@mroderick I would be happy to send a PR for this api.

**Comment by mroderick** [comment]
@zamhaq please go ahead :)

**Comment by mroderick** [comment]
@pkalwar do the new methods in `v1.8.0` meet your needs?

**Comment by maugustosemperfi** [comment]
> @pkalwar do the new methods in `v1.8.0` meet your needs?

I think that PR 155 fulfill our needs about this issue, @mroderick.

**Comment by mroderick** [comment]
Cheers @maugustosemperfi!

I'll close this issue then
