### ISSUE TITLE
unsubscribe 

### ISSUE THREAD

**Issue by nanyanchao** [mroderick/PubSubJS#148]
**my code**
PubSub.subscribe("mytopic", () => { })
PubSub.subscribe("mytopic2", () => { })
PubSub.subscribe("mytopic3", () => { })

**source**
PubSub.subscribe >>>  
if (!messages.hasOwnProperty(message)) {
    messages[message] = {};
}
var token = 'uid_' + String(++lastUid);
messages[message][token] = func;

**my code**
PubSub.unsubscribe("mytopic", () => { })

**source**
PubSub.clearSubscriptions  >>>
for (m in messages) {
    if (messages.hasOwnProperty(m) && m.indexOf(topic) === 0) {
        delete messages[m];
    }
}

so unsubscribe mytopic*

**Comment by bigbigDreamer** [comment]
这种问题就不要提出来了吧，用工具，请先完整的阅读API。
