### ISSUE TITLE
Creating instances

### ISSUE THREAD

**Issue by otto-dev** [mroderick/PubSubJS#149]
Follow up on #6 (years ago). Rejected because "no need"/"will create confusion".

In many use cases it's a requirement to be able to create instances of `PubSub`, in contrast to the current singleton approach.

Example: PubSub might be used within a React component for internal communication. Re-using the React component within the same application will lead to unexpected behaviour (to say the least) because the components are unwittingly communicating with each other. Each component should be able to have it's own, scoped `PubSub` instance.

**Comment by enigma1** [comment]
I am not sure I understand this very well, If say there is a common react component (eg myCard) it will create a separate subscription for its instance. Why it will be a problem as the token retrieved for each instance will be different.

Creating different instances of `PubSub` I think too it will be messy.

**Comment by mroderick** [comment]
> In many use cases it's a requirement to be able to create instances of `PubSub`, in contrast to the current singleton approach.

If those are you needs, you should not be using PubSub, but something like event emitter, which can be instantiated.

See: https://github.com/medikoo/event-emitter
