### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by mtsee** [mroderick/PubSubJS#152]
What is the difference between PubSubJS and EventEmitter?

**Comment by mroderick** [comment]
EventEmitter allows you to publish events on a particular instance of things.
Publish/subscribe allows loose coupling between publishers and subscribers of messages via a broker that both know about.

* https://nodejs.org/api/events.html#events_class_eventemitter
* https://en.wikipedia.org/wiki/Publish–subscribe_pattern
