### ISSUE TITLE
a suggestion about code writing more concise

### ISSUE THREAD

**Issue by liqianglog** [mroderick/PubSubJS#180]
Now it's：
`PubSub.subscribe(‘xxx’,(msg,data)=>{this.xxx(data)})`
After position replacement：
`PubSub.subscribe(‘xxx’,(data,msg)=>{this.xxx(data)})`
It can be abbreviated as：
`PubSub.subscribe(‘xxx’,this.xxx)`

I  have a high degree of simplicity in code. So in my opinion,  it can be more concise after adjustment here. I hope my suggestion can be adopted.

**Comment by mroderick** [comment]
That would be breaking backwards compatibility for all the existing users.

If you change the signature of your `this.xxx` from `this.xxx(data)` to `this.xxx(msg, data)`, then you can still do `PubSub.subscribe(‘xxx’,this.xxx)`
