### ISSUE TITLE
Best way to clean up a subscription on call?

### ISSUE THREAD

**Issue by julianeden** [mroderick/PubSubJS#183]
I have a case where 1 of 2 different possible mutually-exclusive events must be handled, but only once, and then both listeners removed. Those two possible events have different handlers. So I need to listen for both, then remove both listeners when either one is received. Basic idea in code:

```
const handlerA = () => {
  // event-handling code omitted
  // then cancel both listeners
  PubSub.unsubscribe(handlerA);
  PubSub.unsubscribe(handlerB);
};

const handlerB = () => {
  // event-handling code omitted
  // then cancel both listeners
  PubSub.unsubscribe(handlerA);
  PubSub.unsubscribe(handlerB);
};

PubSub.subscribe(TOPIC_A, handlerA);
PubSub.subscribe(TOPIC_B, handlerB);
```

The problem with the above example is that it feels grimy to reference something before it's been declared, as the unsubscribe(handlerB) line is doing inside handlerA. Is there a better way of doing this?

**Comment by mroderick** [comment]
You could store the tokens returned from `PubSub.subscribe` in an array, and have a shared function for unsubscribing all tokens.

This way your functions do not need to know about each other.

```js
const handlerA = () => {
  // event-handling code omitted
  unsubscribeAll();
};

const handlerB = () => {
  // event-handling code omitted
  unsubscribeAll();
};

// function declarations are hoisted, making it safe to reference the function before it is declared
function unsubscribeAll() {
    tokens.forEach(PubSub.unsubscribe);
}

const tokens = [
  PubSub.subscribe(TOPIC_A, handlerA),
  PubSub.subscribe(TOPIC_B, handlerB);
];
```

See http://adripofjavascript.com/blog/drips/variable-and-function-hoisting.html for a good explanation of variable and function hoisting.

**Comment by julianeden** [comment]
I actually did try to take advantage of hoisting in exactly that manner before asking, but typescript in strict mode disallows that. But I pull it off in a slightly different way by just declaring tokens first and appending to it, and declaring unsubscribeAll before the handlers. Just wasn't sure if there was some cleaner way to do it. Thank you for the lightning fast response! Literally the fastest a repo maintainer has ever replied to me. Gold medal!
