### ISSUE TITLE
Waiting for subscriber to finish executing

### ISSUE THREAD

**Issue by manwithsteelnerves** [mroderick/PubSubJS#185]
I'm currently using publishSync and accidentally expected that it waits till the subscriber finishes executing. 

Ideally that how i want to use as I need to instantly finish the processing of all listeners when using publishSync.

I understand that its not a await/async/promise compatible but incase if i need to make my published event to wait until the subscribers finish processing, how can I do that?

Ex:
..code block A
await publishSync('eventname');
..code block B

**Order of events**
1. code block A
2. Notify event with publish sync => Finish processing of event listener async callbacks
3. code block B

**Current functionality**
1. code block A
2. Notify event with publish sync
3. code block B
...
4. Finishing processing of event listener async callbacks

**Comment by mroderick** [comment]
Knowing when an async subscriber has finished processing based on a message, is equivalent to knowing the return value of a subscriber (a `Promise`).

I don't think publish/subscribe is a good pattern to use in this scenario, as it is intended to be used for loose coupling, where many publishers could trigger many subscribers.

In your case I'd recommend coupling the caller and the callee closer together, i.e. calling the callee direrctly. That gives you fine grained control and allows you to use modern JS features such as `async/await` or promise libraries such as Bluebird.

Hope this helps.
