### ISSUE TITLE
Import vs window - unpredictable publishers

### ISSUE THREAD

**Issue by omzeton** [mroderick/PubSubJS#189]
Hi there! I'm using PubSub with Vue to communicate between multiple app instances and also for Vue - Django communication. I followed the docs and setup all of my subscribers via import like so:

```js
import PubSub from 'pubsub-js';
PubSub.subscribe('toggleSaveForLaterModal', (tag, data) => { ... });
```

However as for publishers it's very unpredictable when they work and when they don't. For instance, in my Vuex store imported PubSub stops working and begins to function **only** when called from window like:

```js
window.PubSub.publish('toggleSaveForLaterModal', {...});
```

But sometimes window doesn't work and imports start working again like in all of my Vue components and some, but not all, .js files:

```js
PubSub.publish('toggleSaveForLaterModal', {...});
```

And sometimes they don't work at all, no matter import or window. I'm 100% sure I'm passing the right tag.

What could be the reason behind this unpredictable behaviour? Is it possible that some of my subscriptions are being overwritten or even destroyed whenever I import pubsub in multiple files?

**Comment by mroderick** [comment]
(edited original post to add syntax highlighting)

**Comment by mroderick** [comment]
Are you using some build system or hot module loader?

PubSub keeps its own state, so if it is reloaded, perhaps when another app instance is loading, then the subscriptions would disappear.

One thing you could try, is to load PubSub from a CDN and then not load it using your build system or module loader. If it starts working, then the above hypothesis might be correct.

**Comment by omzeton** [comment]
Indeed I'm heavily using Webpack and just as you wrote after including CDN link and removing all imports to PubSub it all started to work perfectly again (without the use of window of course). Hooray!

Apparently the builds that finished last in the queue were the ones in which PubSub was working ok and subscriptions from previous ones got lost, which is probably why sometimes it worked and sometimes it didn't.

Awesome, thanks so much for your help! 🔥

**Comment by mroderick** [comment]
I'm glad it worked out for you 🍦

**Comment by FreezingRiver** [comment]
From my practice, import or require PubSub only once at entrance and mount PubSub to window, after that use window.PubSub tu do publish and subscribe
