### ISSUE TITLE
PubSub keep using the initial state value in .subscribe() - ReactJS

### ISSUE THREAD

**Issue by s-patompong** [mroderick/PubSubJS#198]
Scenario:
I have a button that publishes an event. The subscriber of that even does a very simple job, append the data from the event to an array which is the state in React functional component.

Problem:
Somehow the code keeps using the initial state in the .subscribe() method. In the example below, the `modules` variable always print out an empty array even after it has been appended with the new data from the payload.

Code snippet:
```jsx
export default function App() {
    const [modules, setModules] = useState([]);

    // Run only one time
    useEffect(() => {
        PubSub.subscribe(NEW_MODULE, (msg, module) => {
            // Here, the value of modules is always []
            setModules([...modules, module]);
        });
    }, []);

    return (
        <div className="App">
            <button onClick={() => PubSub.publish(NEW_MODULE, SettingModule)}>
                Add module
            </button>
            {modules.map((Module, index) => (
                <Module key={index} />
            ))}
        </div>
    );
}
```

Code sandbox URL:
[https://codesandbox.io/s/react-pubsub-keep-old-state-in-subscribe-o873j?file=/src/App.js](https://codesandbox.io/s/react-pubsub-keep-old-state-in-subscribe-o873j?file=/src/App.js)

Any one got this problem before?

**Comment by s-patompong** [comment]
Found the solution. It was my bad that I left the dependencies array empty.

This is how I fix this. The unsubscribe in return is very important. Without it the subscription will still be active and that will slow down the code.

```jsx
useEffect(() => {
  // Fix 2: Store subscription token in sub variable
  let sub = PubSub.subscribe(NEW_MODULE, (msg, module) => {
    console.log("Current modules state: ", modules);
    // Somehow modules keeps being empty array even after the first concat
    setModules([...modules, module]);
  });

  return () => { // Fix 3: Unsubscribe after re-rendered
    PubSub.unsubscribe(sub);
  };
}, [modules]); // Fix 1: Add modules in the dependencies
```

With this, the modules are now kept appending when I click the add module button.

The code sandbox is updated with this new code at https://codesandbox.io/s/fervent-dew-o873j?file=/src/App.js.

I'll close the issue now.

**Comment by fukemy** [comment]
Hi, I have other problem, I called *** publish*** method from other screen, but this screen can not received this event, can u help?

**Comment by fukemy** [comment]
you explain the problem, the right thing is ***your useEffect does not keep track to current state, so it's will get initiate variable always it's called***, to use newest value, just update your code to:

setModules(prev => [...prev, module]);

No need to add dependency

**Comment by fukemy** [comment]
I think the best way to handle PubSub is write it inside useEffect without dependency
