### ISSUE TITLE
Any tests examples approach on this library? (with React)

### ISSUE THREAD

**Issue by Pablo2904** [mroderick/PubSubJS#199]
Hello,
is there any known approach or example of tests for this lib when using with React + hooks, with jest + enzyme?
Documentation not say anything about it, could be useful to add some examples.
Of course currently struggling to write couple tests for this, and nothing wise coming to my mind, any ideas?

**Comment by mroderick** [comment]
I don't use React, Jest or Enzyme. I'm not aware of any documentation or blog posts about testing the use of it.

You can always add a test subscriber to a topic and verify that it gets called.

I can recommend using https://sinonjs.org (I'm a steward of that project).

```js
const subscriber = sinon.fake();

PubSub.subscribe('some topic', subscriber);

PubSub.publish('some topic', 'apple pie');

// using node's assert
assert(subscriber.calledOnceWith('some topic', 'apple pie'));

// using @sinonjs/referee-sinon
assert.calledOnceWith(subscriber, 'some topic', 'apple pie'));
```

You can add behaviour to the subscriber if you want, to make it take the place of some part of your system, that you don't want to test right now.

```js
const subscriber = sinon.fake((topic, value) => {
  PubSub.publish('I ate', value);
});
```

**Comment by mroderick** [comment]
Feel free to link to good learning resources for using PubSubJS with React, Jest, Enzyme here. I'm sure it'll be useful for others in the same situation.
