### ISSUE TITLE
Rename "PubSub" variable for multiple instances

### ISSUE THREAD

**Issue by martiniert** [mroderick/PubSubJS#208]
In our projects we use an external script that is also using pubsub-js, therefore the two instances are in a race condition about the window.PubSub variable.
Is there any way to handle this? Like overriding the variable name with a param?

**Comment by mroderick** [comment]
Currently, there is no support for loading the script twice.

You could make a PR that detects the existence of `window.PubSub` and then not overwrite it, but instead put a warning in the console using `console.warn`.
