### ISSUE TITLE
Is scoping the callback function possible?

### ISSUE THREAD

**Issue by ichabodcole** [mroderick/PubSubJS#21]
The problem I'm having is that I want to call a method on a class, and that method references variables with in the class. Currently they are out of scope and return undefined.

This is the basic idea $.pubsub("subscribe", "update_stuff", callbackFunc, scopeOfCallBackFunc)
Is it  currently possible to do something like this? Any recommendations?

**Comment by PierBover** [comment]
Another way is to store a reference to the bound function.

```js
let hanlder = myMethod.bind(this)
pubsub.subscribe("hellow", handler)

pubsub.unsubscribe(handlder)
```
