### ISSUE TITLE
ReadMe points to wrong jsdelivr package

### ISSUE THREAD

**Issue by gins3000** [mroderick/PubSubJS#217]
Hi!

In the ReadMe you link to http://www.jsdelivr.com/#!pubsubjs which contains only version 1.0.0, but I think it should point to https://www.jsdelivr.com/package/npm/pubsub-js, which has the most up to date version 1.9.4 and has your name attached to it.

We just had confusion in a project, because somebody trusted the ReadMe, causing a clash in PubSub versions used throughout the project :sweat_smile:

**Comment by gins3000** [comment]
Actually it looks like the link points at somebody else's package (https://github.com/TecHunter/pubsubJS)

**Comment by jimaek** [comment]
That link format is the super old one and the redirect is technically correct "#!pubsubjs" to "pubsubjs". Just need to update docs to the new link format :)

**Comment by olleolleolle** [comment]
@jimaek Good eye! Would you be able to offer a fixing PR? Thanks in advance!

**Comment by jimaek** [comment]
Here you go :) https://github.com/mroderick/PubSubJS/pull/218

**Comment by olleolleolle** [comment]
Fixed in #218! 🎉
