### ISSUE TITLE
PubSub instanceable

### ISSUE THREAD

**Issue by maltmann** [mroderick/PubSubJS#6]
Two ways to access the PubSub component:
- Singleton (already exist)
- multiple instances like 
  ```var event1 = new PubSub();
  var event2 = new PubSub();

```
```

**Comment by KutnerUri** [comment]
@mroderick - while using a global singleton is clearly simpler and more convenient, having the option for specific instances is a good idea. For example, if there are a couple of apps in the same browser, etc.

so +1 for instantiation.

**Comment by mroderick** [comment]
@KutnerUri if that's your need, then you should be using a library that supports that. [`event emitter`](https://github.com/medikoo/event-emitter) is a good choice.
