### ISSUE TITLE
CDN delivers old version

### ISSUE THREAD

**Issue by shibukawa** [mroderick/PubSubJS#80]
CDN provides pubsub.js but it is not the latest version.

```
//cdn.jsdelivr.net/pubsubjs/1.4.2/pubsub.js
```

In addition to that, if README has URL of CDN, it will be more excellent.

**Comment by jimaek** [comment]
jsDelivr supports auto-updates https://github.com/jsdelivr/jsdelivr#auto-updating but we need the min file to be added to the repo to enable it.

**Comment by mroderick** [comment]
Pull requests welcome :-)

**Comment by jimaek** [comment]
In this case it has to go out with each version release. So it has to be part of the deployment process before you tag them. If you point me to right direction I could try to add a minification step to it.

**Comment by shibukawa** [comment]
I made pull request for CDN description: https://github.com/mroderick/PubSubJS/pull/82

**Comment by mroderick** [comment]
> I made pull request for CDN description: #82

Is that pull request related to this particular issue, or just to inform people that the module is on a CDN?
