### ISSUE TITLE
Potential Memory leak and a potential fix

### ISSUE THREAD

**Issue by DanAvni** [mroderick/PubSubJS#91]
I have came across a potential memory leak in this scenario:
Frameset page that hosts PubSub
Frame 1 loads page 1, and connects to the PubSub on the frameset
`window.PubSub = top.PubSub;`
Frame 2 loads page 2 and connects to PubSub on the frameset
`window.PubSub = top.PubSub;`
the frames can now send messages to one another without any problem

now Frame 1 loads page 3 that connects to the PubSub on the frameset but without page 1 unsubscribing first.
Now when frame 2 tries to send a message to frame 1 there are actually two listeners in the delivery: 1 and 3. When delivery is attempted to 1 weird things happen:
on FF it passes without any exception but nothing actually happens
on IE an exception is thrown -2146823277 “Can't execute code from a freed script”. When inspecting the code the function pointer is still there with all code so actually the DOM is still held for the page. the reason for this error according to some posts online is that the window hosting the script has been closed/removed (which is correct as the frame contents has been replaced)

obviously if a lot of pages subscribe but never unsubscribe before being replaced there will be a big memory leak. My suggestion for a fix (which will work on IE at least) is to catch the specific exception -2146823277 when trying to invoke the subscriber and if caught remove the subscriber from the list of subscribers.
I am not sure how the same could be done on FF/Chrome as they do not throw an exception and I have not found a way to check if the window is still alive (except maybe when subscribing provide the window object the function is on and then check if that object is still alive or not)

**Comment by mroderick** [comment]
I would recommend that you remove subscriptions before unloading the page.

[`unbeforeunload`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) is widely supported

**Comment by mroderick** [comment]
Or, you could use [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to send messages on channels between frames

**Comment by DanAvni** [comment]
I will use the onbeforeunload but I am more worried about the what if scenario that the event does not fire or does not unregister all. finding a memory leak would be very hard to detect were the missing function pointer came from. that is why I thought about having a "auto cleanup" of missing function handlers.

**Comment by mroderick** [comment]
Can we close this issue?
