### ISSUE TITLE
.publishSync() to return the return of subscribers

### ISSUE THREAD

**Issue by m3talstorm** [mroderick/PubSubJS#92]
Would it be in the spirit of PubSub to add the ability to capture the return value of subscribers when doing synchronous publishes? Like so:

```
PubSub.subscribe('event', function(data) {
    return 1;
});

PubSub.subscribe('event', function(data) {
    return 2;
});

PubSub.subscribe('event', function(data) {
    return 3;
});

PubSub.subscribe('event.something', function(data) {
    return 4;
});

var results = PubSub.publishSync('event.something', { data: 1 })

> results
> [1, 2, 3, 4]
```

This does have some use cases, such as in a plugin/hook architecture. A way of doing this currently would be for each subscriber to touch a global variable, which doesn't seem all that nice.

I would suggest

```
        if ( sync === true ){
            deliver();
```

to change to:

```
        if ( sync === true ){
            return deliver();
```

and then each _callSubscriber_ inside of _deliverMessage_ to append to a list and return that, then subsequently _deliverMessage_ to concatenate the lists. Returning an object may be better, with the keys denoting the message name. Eg:

```
> results
> {
    event: [1, 2, 3],
    event.something: [4],
}
```

The signature of  _.publishSync()_ would change slightly, but code doing a truthy/falsy check on its current return value (true/false) should still continue to work.

Thoughts?

**Comment by 8427003** [comment]
+1

**Comment by VoltiSubito** [comment]
I know this is an old thread but my .02 on this is if the publisher (or anyone else) is interested in the work a subscriber is doing, that subscriber should publish on a different topic (event) with its results.

**Comment by mroderick** [comment]
I agree with @VoltiSubito's approach to solving this challenge.

**Comment by m3talstorm** [comment]
Seems like the this defeats the purpose of having a synchronous function if that value is returned asynchronously.
