### ISSUE TITLE
Before I write the before function

### ISSUE THREAD

**Issue by johngeorgewright** [mroderick/PubSubJS#93]
Hey there,

I'm considering writing a project specific extension to you package, but before I did, I thought I'd throw the idea your way to see if you'd want to include such a feature.

In a specific scenario, I require to pause the publication of an event while something else happens. I was considering writing a "before" function. It might look something like:

```javascript
before('someMessage', (message, data, done) => {
  // Once "someMessage" is published, none of the subscribers will
  // be notified until I call `done()`
  doSomethingAsynchronous().then(done);
});
```

No worries if this is not suitable for your package, but if it is, it would save forking.

Ta.

**Comment by mroderick** [comment]
Hey @johngeorgewright 

I don't think this will be a good fit for my ambitions for the project.

A fork is a better idea.

Cheers!

/Morgan
