### ISSUE TITLE
Pass the msg as the second argument

### ISSUE THREAD

**Issue by amatiash** [mroderick/PubSubJS#95]
I would recommend to pass `msg` as a second argument. Because you are supposed to use `data` first. And that becomes very annoying to rewrite APIs to skip the `msg` argument and to see the editor's highlighting of unused local variable.

So, instead of:

`var mySubscriber = function( msg, data ){
    // do something with data
};`

do this:

`var mySubscriber = function( data ){
    // do something with data
};`

Isn't it better?

**Comment by amatiash** [comment]
I guess it was made similar to jQuery `.on()`, so it passes an event as a first argument to the callback, right?

**Comment by mroderick** [comment]
If your editor (or linter) can't detect that the first argument is necessary to declare the second argument, then you should get a better one.

http://eslint.org detects this just fine
