### ISSUE TITLE
Why window.PubSub is not the same object returned by require('pubsub-js')?

### ISSUE THREAD

**Issue by lorenzos** [mroderick/PubSubJS#99]
Any reason why:

    var PubSub = require('pubsub-js');
    PubSub === window.PubSub; // false

I see in the first line of the [source file](https://github.com/mroderick/PubSubJS/blob/master/src/pubsub.js#L16) that `factory()` is called twice, one for AMD/CommonJS (lines 12 and 16) and one for the browser (line 23). That way the two objects are not the same, and so you cannot use `require('pubsub-js')` and `window.PubSub` interchangeably.

Isn't possible to make it so, creating a single unique singleton object accross AMD/CommonJS **and** browser?

**Comment by pmorch** [comment]
I just got bitten by a variation of this too - I'm just using AMD with requirejs.

You cannot mix and match them. Put require.js, pubsub.js and this HTML file in the same directory:

    <!DOCTYPE HTML>
    <html>
    <head>
        <script type="text/javascript" src="require.js"></script>
        <script>
            require(['pubsub'], function (PubSub) {
                // PubSub in this scope (given as param from require) is not the
                // same as window.PubSub, and maintain different sets of
                // subscriptions, which is surprising
                PubSub.subscribe(
                    'myEvent', function (name, value) {
                        console.log("required subscription", name, value);
                    }
                );
                window.PubSub.subscribe(
                    'myEvent', function (name, value) {
                        console.log("global subscription", name, value);
                    }
                );
                PubSub.publish('myEvent', 'required publish');
                window.PubSub.publish('myEvent', 'global publish');
            });
        </script>
    </head>
    <body>
    </body>
    </html>

It prints this in the console:

```
requrired subscription myEvent required publish
global subscription myEvent global publish
```

I was definitely expecting four lines of input: Both subscriptions should be called for both publishes.

Or - _at least_ - pubsub.js shouldn't set a global variable when being `required`d.
